### ISSUE TITLE
Hitless reload not working

### ISSUE THREAD

**Issue by shawkins** [openshift/router#429]
On openshift 4.10.15 and other recent versions that we've been on the haproxy router pods will accumulate processes from long lived connections unless the ingress.operator.openshift.io/hard-stop-after annotation forces disconnections.  It does not appear that hitless reload, which was supposed to be enabled with https://github.com/openshift/router/commit/5ae85d7c499779f3fd7c90ca6a3cd535e543a22c, is working.  This means that on any update of the haproxy config, such as adding or removing a route, all connections are disconnected.

**Comment by shawkins** [comment]
> What duration do you have set for hard-stop-after (if any)?

Without explicitly setting the hard stop annotation we observed an accumulation of old haproxy processes and thus increasing memory usage similar to what is described with https://bugzilla.redhat.com/show_bug.cgi?id=2007581 - there is seemingly no hand-off of connections from the old process.  We saw total memory usage approaching 2GiB with minimal connection loads - well below the default 20000 max connections.  Am I misunderstanding https://github.com/openshift/router/commit/5ae85d7c499779f3fd7c90ca6a3cd535e543a22c - is it not expected for reloads to be hitless? https://www.haproxy.com/blog/hitless-reloads-with-haproxy-howto/

For an unrelated reason [*] we have set a very short hard stop after time of 5s.  When that 5 seconds expires we do see, somewhat as expected, disconnections.

[*] we are using the haproxy stats to determine ingress/egress usage.  However those seem to only be collected for the latest process making us miss potentially a lot of usage if those old processes hang around for a while.

> Do you have a reproducer at all? I ask because in all the testing that I have done I have not seen the addition or removal of a route to drop all connections in all processes.

It's easily reproducible in our environment, but I have not tried to create an isolated test case.  I can provide whatever configuration or logs are needed.  However this could just be a misunderstanding of how the configuration reload is supposed to work with long lived connections.

**Comment by frobware** [comment]
> For an unrelated reason [*] we have set a very short hard stop after time of 5s. 

This will terminate any haproxy process after it has been running for 5s. Given such a short duration then I can now understand why all connections "appear" to drop.

**Comment by shawkins** [comment]
Can you confirm what is the expected behavior without setting the hard stop annotation?  Should it be like https://bugzilla.redhat.com/show_bug.cgi?id=2007581 with an accumulation of old processes?

**Comment by frobware** [comment]
The `hard-stop-after` annotation is to help control the runaway accumulation of haproxy processes.

If you have frequent router reloads (because endpoints change, or routes are added/deleted, etc) then a new process is started (listening ports 80/443/1936 are transferred from what is about to become the old haproxy process to the new process), incoming connections are now established on this new process (this is the hit-less part), but both processes continue to run.

Old processes cannot exit until all established connections are dropped/closed. If the client represents a long-lived connect (i.e., a websocket) then this could remain established indefinitely. The pattern "create new process, transfer listening sockets, old process remains until all connections established to that process are dropped" occurs for every router reload. If, in old processes, all the clients disconnect it will exit immediately; it doesn't wait for the `hard-stop-after` duration to expire.

`hard-stop-after` was added so that cluster administrators can choose to forcibly disconnect established connections (in old processes) after some time period. If your traffic includes long-lived connections--and you have frequent reloads--then you will accumulate lots of old processes (assuming `hard-stop-after` is not set).

In the past I have advocated setting `hard-stop-after` to 30 mins. Given your traffic and the nature of the established connections (i.e., websockets), and also the frequency of router reloads, 30 mins may be too short / too long. 

If the `hard-stop-after` duration is too long, and you have frequent reloads, then you will accumulate a lot of processes; your pod could eventually be OOMKilled due to memory pressure. That would obviously drop all connections too.

**Comment by frobware** [comment]
> This is the part that confuses me. The other descriptions of hitless reload, enabled via the expose-fd listeners, describe it as transferring old connections to the new process:

Just looking at the citations you've quoted from the links, they all mention "listening sockets (i.e., ports 80/443/1936, the stats socket)", but not established connections. If you have, say, 100000 established connections, then even it if was actually possible to transfer established connections, that could potentially add some latency).

I don't know if the master/worker model behaves differently as we don't use that mechanism in OpenShift. (And I've never really experimented with the master/worker model in general.)

**Comment by shawkins** [comment]
> Just looking at the citations you've quoted from the links, they all mention "listening sockets (i.e., ports 80/443/1936, the stats socket)", but not established connections

Ah, so this is a misunderstanding - the old process is still stuck with the old connections.

> I don't know if the master/worker model behaves differently as we don't use that mechanism in OpenShift. (And I've never really experimented with the master/worker model in general.)

I was wondering that, but from the descriptions it just seems that handles the process launches.

Do you have any suggestion on what could initiate an more orderly draining of old long-living connections over a relatively short time period, rather than forcing just a hard stop?

**Comment by shawkins** [comment]
> Do you have any suggestion on what could initiate an more orderly draining of old long-living connections over a relatively short time period, rather than forcing just a hard stop?

It sounds like this is not possible either, so we're mostly stuck with the present behavior.

Marking as closed - thank you for the explanations.
