### ISSUE TITLE
Replace `clipHAProxyTimeoutValue (firstMatch $timeSpecPattern foo)` with `clipHAProxyTimeoutValue foo` in `haproxy-config.template` as an optimization.

### ISSUE THREAD

**Issue by candita** [openshift/router#494]
BTW, as a follow-up, it might make sense to replace `clipHAProxyTimeoutValue (firstMatch $timeSpecPattern foo)` with `clipHAProxyTimeoutValue foo` in `haproxy-config.template` as an optimization.

_Originally posted by @Miciah in https://github.com/openshift/router/pull/483#pullrequestreview-1484951102_

**Comment by rfredette** [comment]
This should probably be filed as a maintainability issue, unless there’s a customer with a real-world issue due to the haproxy template taking too long to write. 

It would also be useful to have some sort of testing to quantify how long writing the template takes, either as a part of the same issue or as a separate one.
