### ISSUE TITLE
Missing openshift_default backend servers?

### ISSUE THREAD

**Issue by david-shepard** [openshift/router#62]
For a few of the frontend's it seems the `default_backend` is `openshift_default`. However it looks like there are [no servers](https://github.com/openshift/router/blob/master/images/router/haproxy/conf/haproxy-config.template#L354-L358) listed under the `openshift_default` backend heading. This leads to 503 errors under certain conditions (if a request falls through the ACL rules to `default_backend`).

For example if an non-SNI SSL request comes through and you have termination passthrough it will fall through to the `default_backend` and the server will return a 503. 

Similar to what is described here: https://github.com/openshift/origin/issues/23223.

**Comment by germanattanasio** [comment]
I'm running into the same problem when trying to use SNI 😭

**Comment by ahlae** [comment]
We are seeing this too when deploying custom certificates from Let's Encrypt. After the router redeployed we see this in the haproxy-logs when someone wants to log in or out from the webconsole using openid:

```
fe_sni~ be_secure:openshift-console:console/pod:console-d59d9d588-6stps:console:10.129.0.94:8443 0/0/0/5/5 303 859 - - --VN 18/8/6/0/0 0/0 "GET /auth/login HTTP/2.0"

fe_sni~ openshift_default/<NOSRV> 0/-1/-1/-1/0 503 3288 - - SC-- 18/8/0/0/0 0/0 "GET /oauth/authorize?client_id=console&redirect_uri=https%3A%2F%2Fconsole-openshift-console.apps.okd.cluster...%2Fauth%2Fcallback&response_type=code&scope=user%3Afull&state=63835a61 HTTP/2.0"
```
Only a hard browser refresh (shift+reload) helps after that and produces the following output:

```
fe_sni~ be_secure:openshift-console:console/pod:console-d59d9d588-6stps:console:10.129.0.94:8443 0/0/0/5/5 303 859 - - --VN 18/8/6/0/0 0/0 "GET /auth/login HTTP/2.0"

public_ssl be_tcp:openshift-authentication:oauth-openshift/pod:oauth-openshift-75cf59f6f5-kfkgk:oauth-openshift:10.129.0.98:6443 1/1/36572 110754 -- 31/16/0/0/0 0/0
```
It seems to me it might be the redirect 303 produced from the webconsole which causes haproxy to fall through to the default_backend. Strangely this doesn't happen with the original Openshift certificates.

That's why it might also be because we have more Subject Alternative Names in the cert in addition to api.cluster.domain and *.apps.cluster.domain?

Is there any workaround for this?
